baseurl         = "/"
theme           = "casper-two"
languageCode    = "en-US"
disqusShortname = ""
paginate        = 6
#SectionPagesMenu = "main"
canonifyurls    = true
publishDir = "../"

[params]
  title       = "Programistata"
  subtitle    = "Tata o rodzinie"
  copyright   = "© 2018"

  cover       = "img/cover-4.jpg"
  description = ""
  metaDescription = ""
  googleAnalytics = ""
  customCSS = []
  RSSLink = ""

  twitterName = ""
  fbName = "programistata"
  instagramName = "programistata"
  githubName = ""
  linkedinName = ""
  mediumName = ""

  logo = "img/logo-withtext.png"
  orgName = "Programistata"
  orgWebsite = ""
  orgDescription = ""

  showSupport = true

  author = "Krzysztof Seroka"
  authorAvatar = "img/ghost-icon.png"
  authorLocation = "Kraków"
  authorWebsite = "https://chrisseroka.wordpress.com"
  authorDescription = "Programista, Tata"

  pageNotFoundTitle = "404 - Nie ma takiej strony"

  #casper or caspertwo
  singleViewStyle = "casper"

[permalinks]
  post = "/post/:slug/"

[[menu.main]]
  name = "Główna"
  url = "/"
  weight = 200

[[menu.main]]
  name = "Pozytywna dyscyplina"
  url = "/tags/golang/"
  weight = 100

[[menu.main]]
  name = "Czas z dzieckiem"
  url = "/tags/golang/"
  weight = 99

[[menu.main]]
  name = "Warsztaty"
  url = "/tags/golang/"
  weight = 90

[[menu.main]]
  name = "O mnie"
  url = "/about/"
  weight = 10

